services:
  - type: web
    name: ec2-cost-optimization-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python dashboard/app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.8
